### ISSUE TITLE
heatmap has hardcoded sample names

### ISSUE THREAD

**Issue by sneumann** [ipb-halle/biobyte#1]
Hi, following comments after last BioByte, we should remove the explicit 
Sample names indicating Blut Or Ketchup. 
We now have https://github.com/ipb-halle/biobyte/blob/master/feat_list_log.tsv
and https://github.com/ipb-halle/biobyte/blob/master/feat_list.tsv
but the `heatmap.r` has hardcoded sample names instead of the data matrix
column names:
https://github.com/ipb-halle/biobyte/blob/master/scripts/heatmap.r#L79
Yours, Steffen

**Comment by korseby** [comment]
Hi,

change line 39 to: `ketchup_samples <- colnames(feat_list)`

https://github.com/ipb-halle/biobyte/blob/master/scripts/heatmap.r#L39

**Comment by sneumann** [comment]
Thanks, Fixed in 3a43affcc05aab3b706b203333fd51853b70ee81
